name: pepland-inference
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - rdkit
  - numpy
  - pandas
  - omegaconf
  - pyyaml
  - pip:
    - torch==1.11.0+cu113 -f https://download.pytorch.org/whl/cu113
    - dgl-cu113==0.9.1 -f https://data.dgl.ai/wheels/repo.html
    - mlflow==1.30.0
    - cloudpickle==2.2.1
    - scikit-learn
